//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int Id { get; set; }
        public string ArContact { get; set; }
        public string EnContact { get; set; }
        public string Fb { get; set; }
        public string youtube { get; set; }
        public string tweeter { get; set; }
        public string googleplus { get; set; }
        public string linkedIn { get; set; }
        public string instegram { get; set; }
    }
}
