//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs
    {
        public int Id { get; set; }
        public string phoneNumber { get; set; }
        public string Email { get; set; }
        public string ArAddress { get; set; }
        public string EnAddress { get; set; }
        public string ArExplain { get; set; }
        public string EnExplain { get; set; }
    }
}
