//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contury
    {
        public Contury()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int Id { get; set; }
        public string ContryName { get; set; }
        public string ArDecription { get; set; }
        public string ArContryName { get; set; }
        public string EnDescription { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
}
