//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurNews
    {
        public int Id { get; set; }
        public string DateOf { get; set; }
        public string ArCaption { get; set; }
        public string ArSummary { get; set; }
        public string ArDetails { get; set; }
        public string Photo { get; set; }
        public string EnCaption { get; set; }
        public string EnSummary { get; set; }
        public string EnDetails { get; set; }
    }
}
