//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataController
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteInfo
    {
        public int Id { get; set; }
        public string WebSiteName { get; set; }
        public string WebSitDescription { get; set; }
        public string WebsiteTags { get; set; }
        public string DefaultLanguge { get; set; }
    }
}
